#!/usr/bin/env sh

# reset permissions
chown -R logstash:logstash /opt/logstash

exec s6-setuidgid logstash \
                  java \
                  -Xmx1g \
                  -Xms256m \
                  -Xss2048k \
                  -classpath : \
                  -XX:+UseParNewGC \
                  -XX:+UseConcMarkSweepGC \
                  -XX:CMSInitiatingOccupancyFraction=75 \
                  -XX:+UseCMSInitiatingOccupancyOnly \
                  -XX:+DisableExplicitGC \
                  -XX:+HeapDumpOnOutOfMemoryError \
                  -Xbootclasspath/a:/opt/logstash/vendor/jruby/lib/jruby.jar \
                  -Djffi.boot.library.path=/opt/logstash/vendor/jruby/lib/jni \
                  -Djava.awt.headless=true \
                  -Dfile.encoding=UTF-8 \
                  -Djruby.home=/opt/logstash/vendor/jruby \
                  -Djruby.lib=/opt/logstash/vendor/jruby/lib \
                  -Djruby.script=jruby \
                  -Djruby.shell=/bin/sh \
                  org.jruby.Main --1.9 \
                  /opt/logstash/lib/bootstrap/environment.rb \
                  logstash/runner.rb -f /etc/logstash/logstash.conf 2>&1
