#!/usr/bin/env sh

# reset permissions after docker volume remount
chown -R elasticsearch:elasticsearch /var/lib/elasticsearch /opt/elasticsearch

# java wat doe je met mij?
exec s6-setuidgid elasticsearch \
                  java \
                  -server \
                  -Xms2g \
                  -Xmx2g \
                  -XX:+UseConcMarkSweepGC \
                  -XX:CMSInitiatingOccupancyFraction=75 \
                  -XX:+UseCMSInitiatingOccupancyOnly \
                  -XX:+DisableExplicitGC \
                  -XX:+AlwaysPreTouch \
                  -XX:+HeapDumpOnOutOfMemoryError \
                  -Djava.awt.headless=true \
                  -Dfile.encoding=UTF-8 \
                  -Djna.nosys=true \
                  -Dio.netty.noUnsafe=true \
                  -Dio.netty.noKeySetOptimization=true \
                  -Dlog4j.shutdownHookEnabled=false \
                  -Dlog4j2.disable.jmx=true \
                  -Dlog4j.skipJansi=true \
                  -Des.path.home=/opt/elasticsearch \
                  -cp /opt/elasticsearch/lib/elasticsearch-5.3.0.jar:/opt/elasticsearch/lib/* \
                  org.elasticsearch.bootstrap.Elasticsearch 2>&1
